FROM node:21-alpine3.17

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

ENV SYSTEMNAME=my-system-name
ENV USERNAME=my-username
ENV PASSWORD=my-password
ENV DOWNLOAD_LOCATION=my-download-location
ENV PORT=3000

RUN npm run build

CMD [ "node", "./dist/Index.js" ]